import axios from 'axios';


const ruby_tasks_low = [{compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 1##223", taskDescription: "heeey", expectedOutput: 5, completed: true }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 2#5784", taskDescription: "heeeyo", expectedOutput: 3, completed: true }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 3#84523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 4#dsgs31de3", taskDescription: "hepeey", expectedOutput: 5, completed: false }]
const ruby_tasks_medium = [{compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 1#232", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 2#7685569", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 3#8453223", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 4#ds312gsde3", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const ruby_tasks_advanced = [{compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 1#5346", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Ruby", taskName: "this is name of task 2#3475659", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 3#84444523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Ruby", taskName: "this is name of task 4#ds3123gsde3", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const python_tasks_low = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 1#856563", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 2#5678", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 3#84552323", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 4#dsgs5323de3", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 5#31312ycasd", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 6#3131asd2asd", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 7#wddddefd", taskDescription: "heay", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 8#dasd", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const python_tasks_medium = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 1#53457", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 2#34565", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 3#84562323", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 4#dsg231sde3", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 5#31312asxd", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 6#313da12asd", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 7#wdadfd", taskDescription: "heay", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 8#aaa", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const python_tasks_advanced = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 1#454363", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 2#5637", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text",  technology: "Python",taskName: "this is name of task 3#84552323", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 4#dsg3123sde3", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 5#31312casd", taskDescription: "heeey", expectedOutput: 5, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Python", taskName: "this is name of task 6#313aa12asd", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 7#wdadfd", taskDescription: "heay", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Python", taskName: "this is name of task 8#312", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const cplusplus_tasks_low = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 1#52463", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 2#45672", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 3#8462523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Cplusplus", taskName: "this is name of task 4#dsgsd3123e3", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const cplusplus_tasks_medium = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 1#42367", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 2#12365441", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 3#8444523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Cplusplus", taskName: "this is name of task 4#ds3123gsde3", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const cplusplus_tasks_advanced = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 1#23678", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 2#26374", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {enteredCode: "default text", technology: "Cplusplus", taskName: "this is name of task 3#8234523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology:"Cplusplus", taskName: "this is name of task 4#dsgsde23123", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const csharp_tasks_low = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 1#96754", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 2#5367486", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 3#84323523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 4#dsgsde22313", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const csharp_tasks_medium = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 1#6789", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 2#5678qq", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 3#824523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 4#dsgsde311", taskDescription: "hepeey", expectedOutput: 5, completed:false }]
const csharp_tasks_advanced = [{compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 1#1279", taskDescription: "heeey", expectedOutput: 5, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 2#5627sg", taskDescription: "heeeyo", expectedOutput: 3, completed:false }, {ecompiledCode: "Click button to compile", nteredCode: "default text", technology: "Csharp", taskName: "this is name of task 3#843523", taskDescription: "heay", expectedOutput: 3, completed: false }, {compiledCode: "Click button to compile", enteredCode: "default text", technology: "Csharp", taskName: "this is name of task 4#dsgsde3123", taskDescription: "hepeey", expectedOutput: 5, completed:false }]


const getAllTasks = () => {
    let x = null;
    console.log('posting....');
    axios.get('http://localhost:5000/assesmentTasksFrontend/tasks')
    .then(res => {
       x = res.data;
       console.log(x);
       let y = Object.assign({}, x[0]);
       delete y["_id"];
       console.log(y);
       return y
      })
    .catch(err => {
      console.log(err);
      return null });
}

const myDatabase = getAllTasks();

export default myDatabase;